### ISSUE TITLE
fps not working correctly

### ISSUE THREAD

**Issue by syberant** [splintah/game-of-life#2]
The `game_of_life.update()` function gets called a lot more than it should, based on the generation.
Try adding `window.set_title(game_of_life.generation.to_string());` to the event loop, uncomment the generation counting system and pass `--fps 1` and it's pretty obvious. The effect is especially noticeable when you move your mouse cursor.

To fix this more should be learnt about what events actually get processed by the event loop and how to filter them.

**Comment by splintah** [comment]
Maybe `game_of_life.update()` should be moved to the drawing function, like:
```rust
window.draw_2d(&e, |c, g| {
    // ... snip ...
    game_of_life.update();
});
```

**Comment by splintah** [comment]
> Maybe game_of_life.update() should be moved to the drawing function?

In bdd6661 I've done this, it seemed to improve performance.

**Comment by syberant** [comment]
> Maybe game_of_life.update() should be moved to the drawing function?

I know that's a solution, it's why I originally put it there before you reverted my change.

> Also, when passing --fps 1, the updating happens only once per second.

That's curious, it really didn't on my build (when it wasn't in the `draw_2d()`) and I checked it with `println!("{:?}", e);`.
The `draw_2d()` doesn't run it's closure unless `&e` is a render event.

I think I fixed it in [this](https://github.com/syberant/game-of-life-1/tree/update-mechanism) branch, should I create a pull request?

**Comment by splintah** [comment]
> That's curious, it really didn't on my build (when it wasn't in the draw_2d()) and I checked it with println!("{:?}", e);.

No, I meant when it was inside the draw_2d closure.

> I think I fixed it in this branch, should I create a pull request?

The current implementation works fine for me, so I think that's not necessary. I will close this now, but if you think there still is a problem, please reopen.
